spring:
  datasource:
    url: jdbc:mysql://localhost:3306/charger?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8080

springdoc:
  api-docs:
    path: /v3/api-docs # OpenAPI 文档的路径
  swagger-ui:
    path: /swagger-ui.html # Swagger UI 的路径

app:
 time-scale-factor: 60
 fast-pile-num: 3
 slow-pile-num: 3
 waiting-area-capacity: 6
 pile-queue-length: 2